### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by hasenbanck** [Gonkalbell/egui_winit_wgpu#1]
Hi!

Thank you for your work on bringing egui to wgpu. Since I'm currently porting my game to egui and planing to use advance features (bindless) in the GUI path as well, I have to write my own backend sooner or later.

I have seen that you are currently naming this crate "egui_wgpu", but decided to use winit as a windowing platform. Could you maybe change the name of the crate to reflect that? Reasons is:

It's possible to provide a drawing backend for egui and a windowing / input platform for egui. Currently the provided crates don't distinguish them (because in case of glium / web this doesn't make much sense), but with wgpu you could use many platforms (winit, kapp, glium, web etc.). I'm not against the idea to provide library that bundles both the backend and the platform code into one convinient wrapper, but if we later have  libraries that just provides a wgpu backend  or a wninit platform or a kapp platform or even opengl3 backend, this could lead to confusion.

**Comment by Gonkalbell** [comment]
That definitely sounds like a good idea to rename this crate. I'd actually like to go a bit further and separate the graphics and windowing backends, like how imgui separates them. But renaming this seems like a good first step
